spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/akutsev
    username: postgres
    password: alex

    initialization-mode: always

    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    show-sql: true

  batch:
    initialize-schema: always
    job:
      enabled: true

  data:
    mongodb:
      database: library