DROP TABLE IF EXISTS GENRES CASCADE;
DROP TABLE IF EXISTS AUTHORS CASCADE;
DROP TABLE IF EXISTS BOOKS CASCADE;
DROP TABLE IF EXISTS COMMENTS;
DROP TABLE IF EXISTS AUTHORITIES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ACL_SID CASCADE ;
DROP TABLE IF EXISTS ACL_CLASS CASCADE ;
DROP TABLE IF EXISTS ACL_ENTRY CASCADE ;
DROP TABLE IF EXISTS ACL_OBJECT_IDENTITY CASCADE;

CREATE TABLE genres (
  ID BIGSERIAL NOT NULL,
  GENRE_NAME VARCHAR(250) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE authors (
  ID BIGSERIAL NOT NULL,
  NAME VARCHAR(250) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE books (
  ID BIGSERIAL NOT NULL,
  NAME VARCHAR(250) NOT NULL,
  AUTHOR_ID BIGINT NOT NULL,
  GENRE_ID BIGINT NOT NULL,
  PRIMARY KEY (ID),
  foreign key (AUTHOR_ID) references authors(ID),
  foreign key (GENRE_ID) references genres(ID)
);

CREATE TABLE comments (
  ID BIGSERIAL NOT NULL,
  TEXT VARCHAR(250) NOT NULL,
  BOOK_ID BIGINT,
  PRIMARY KEY (ID),
  foreign key (BOOK_ID) references books(ID) ON DELETE CASCADE
);

-- SPRING SECURITY USERS

CREATE TABLE USERS (
  USERNAME VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  ENABLED SMALLINT NOT NULL DEFAULT 1,
  PRIMARY KEY (USERNAME)
);

CREATE TABLE AUTHORITIES (
  USERNAME VARCHAR(50) NOT NULL,
  AUTHORITY VARCHAR(50) NOT NULL,
  FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);

-- SPRING SECURITY ACL

CREATE TABLE IF NOT EXISTS ACL_SID (
  ID SERIAL,
  PRINCIPAL BOOLEAN NOT NULL,
  SID VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ACL_CLASS (
  ID SERIAL,
  CLASS VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ACL_ENTRY (
  ID SERIAL,
  ACL_OBJECT_IDENTITY INT NOT NULL,
  ACE_ORDER INT NOT NULL,
  SID BIGINT NOT NULL,
  MASK INT NOT NULL,
  GRANTING BOOLEAN NOT NULL,
  AUDIT_SUCCESS BOOLEAN NOT NULL,
  AUDIT_FAILURE BOOLEAN NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ACL_OBJECT_IDENTITY (
  ID BIGSERIAL,
  OBJECT_ID_CLASS INT NOT NULL,
  OBJECT_ID_IDENTITY varchar(36) NOT NULL,
  PARENT_OBJECT INT DEFAULT NULL,
  OWNER_SID INT DEFAULT NULL,
  ENTRIES_INHERITING BOOLEAN NOT NULL,
  PRIMARY KEY (ID)
);

-- CONSTRAINTS FOR SPRING SECURITY ACL TABLES

ALTER TABLE ACL_ENTRY
ADD FOREIGN KEY (ACL_OBJECT_IDENTITY) REFERENCES ACL_OBJECT_IDENTITY(ID);

ALTER TABLE ACL_ENTRY
ADD FOREIGN KEY (SID) REFERENCES ACL_SID(ID);

ALTER TABLE ACL_OBJECT_IDENTITY
ADD FOREIGN KEY (PARENT_OBJECT) REFERENCES ACL_OBJECT_IDENTITY (ID);

ALTER TABLE ACL_OBJECT_IDENTITY
ADD FOREIGN KEY (OBJECT_ID_CLASS) REFERENCES ACL_CLASS (ID);

ALTER TABLE ACL_OBJECT_IDENTITY
ADD FOREIGN KEY (OWNER_SID) REFERENCES ACL_SID (ID);